=== haikalhabibie33/jatifitness-app/app/Database/Seeds/schema/non-pages/schedule.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "day": {"type":"string"},
            "time": {"type": "string"},
            "activity": {"type": "string"},
            "trainer": {"type": "string"}
        },
        "required": ["day", "time", "activity", "trainer"],
        "additionalProperties": true
    }
}

=== haikalhabibie33/jatifitness-app/app/Database/Seeds/json/non-pages/schedule.json
[
    {
        "day": "Saturday",
        "time": "6am - 8am",
        "activity": "Kick Boxing",
        "trainer": "Alex Travis"
    },
    {
        "day": "Sunday",
        "time": "6am - 8am",
        "activity": "Zumba",
        "trainer": "Marina Laurel"
    },
    {
        "day": "Monday",
        "time": "6am - 8am",
        "activity": "Muay Thai",
        "trainer": "Chris Balder"
    },
    {
        "day": "Tuesday",
        "time": "6am - 8am",
        "activity": "Kick Boxing",
        "trainer": "Alex Travis"
    },
    {
        "day": "Wednesday",
        "time": "6am - 8am",
        "activity": "Zumba",
        "trainer": "Marina Laurel"
    },
    {
        "day": "Thursday",
        "time": "6am - 8am",
        "activity": "Yoga",
        "trainer": "Jennifer O'Keeffe"
    },
    {
        "day": "Friday",
        "time": "6am - 8am",
        "activity": "Aerobic",
        "trainer": "Sienna Nevada"
    }
]
