=== haikalhabibie33/jatifitness-app/app/Database/Seeds/schema/pages/about.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "about_hero_url" : { "type": ["string", "null"]},
        "about_section_title": { "type": ["string", "null"]},
        "about_hero_caption": { "type": ["string", "null"]},
        "about_description_primary": { "type": ["string", "null"]},
        "about_description_secondary": { "type": ["string", "null"]}
    },
    "additionalProperties": true
}

=== haikalhabibie33/jatifitness-app/app/Database/Seeds/json/pages/about.json
{
    "about_hero_url": "assets/img/gallery/about.png",
    "about_section_title": "ABOUT OUR GYM",
    "about_hero_caption": "Safe Body building proper Solutions That Saves our Valuable Time!",
    "about_description_primary": "Brook presents your services with flexible, convenient and cdpose layouts. You can select your favorite layouts & elements for cular ts with unlimited ustomization possibilities. Pixel-perfect replication of the designers is intended.",
    "about_description_secondary": "Brook presents your services with flexible, convefnient and chient anipurpose layouts. You can select your favorite layouts."
}
