=== haikalhabibie33/jatifitness-app/app/Database/Seeds/schema/pages/contact.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "contact_city" : { "type": ["string", "null"]},
        "contact_street": { "type": ["string", "null"]},
        "contact_phone": { "type": ["string", "null"]},
        "contact_availableToPhone": { "type": ["string", "null"]},
        "contact_email": { "type": ["string", "null"]},
        "contact_emailMessage": { "type": ["string", "null"]},
        "contact_facebook_url": { "type": ["string", "null"]},
        "contact_tiktok_url": { "type": ["string", "null"]},
        "contact_instagram_url": { "type": ["string", "null"]}
    },
    "additionalProperties": true
}

=== haikalhabibie33/jatifitness-app/app/Database/Seeds/json/pages/contact.json
{
    "contact_city": "Loa Janan, Samarinda",
    "contact_street": "Jalan Jati 7, Harapan Baru",
    "contact_phone": "+6282130832808",
    "contact_availableToPhone" : "Mon to Fri 9am to 6pm",
    "contact_email": "admin@jatifitness.com",
    "contact_emailMessage": "Send us your query anytime!",
    "contact_facebook_url": "#",
    "contact_tiktok_url": "#", 
    "contact_instagram_url": "https://www.instagram.com/fitjati/"   
}
