=== haikalhabibie33/jatifitness-app/app/Database/Seeds/schema/pages/services.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "type": "object",
    "properties": {
        "services_section_title": { "type": ["string", "null"] },
        "services_hero_caption": { "type": ["string", "null"] },
        "services_quality_equipment_desc": { "type": ["string", "null"] },
        "services_health_caring_desc": { "type": ["string", "null"] },
        "services_gym_strategies_desc": { "type": ["string", "null"] }

    },
    "additionalProperties": true
}

=== haikalhabibie33/jatifitness-app/app/Database/Seeds/json/pages/services.json
{
    "services_section_title": "OUR sERVICES FOR YOU",
    "services_hero_caption": "PUSH YOUR LIMITS FORWARD We Offer to you",
    "services_quality_equipment_desc": "View clear information about gym facilities and available equipment to ensure they match your training needs.",
    "services_health_caring_desc": "Find gyms that support a healthy lifestyle with transparent membership details and direct communication with gym owners.",
    "services_gym_strategies_desc": "Compare gym memberships easily and message gym owners directly to find the best option for you."
}
